Reproducing catalog error when ingesting to path with trailing slash

diff --git a/test/src/701-ingest-trailing-slash/main b/test/src/701-ingest-trailing-slash/main
--- a/test/src/701-ingest-trailing-slash/main
+++ b/test/src/701-ingest-trailing-slash/main
@@ -46,25 +46,25 @@ cvmfs_run_test() {
   mkdir /cvmfs/$CVMFS_TEST_REPO/target
   cvmfs_server publish $CVMFS_TEST_REPO
 
-  echo "*** ingesting the tarball in the root of the repository"
-  cvmfs_server ingest --base_dir / --tar_file $tarfile $CVMFS_TEST_REPO || return $?
+  echo "*** ingesting the tarball in a subdir of the repository (has a trailing slash)"
+  cvmfs_server ingest --base_dir target/ --tar_file $tarfile $CVMFS_TEST_REPO || return $?
 
   echo "*** check catalog and data integrity"
   check_repository $CVMFS_TEST_REPO -i || return $?
 
-  if [ ! -d $repo_dir/tarball_foo ]; then
+  if [ ! -d $repo_dir/target/tarball_foo ]; then
     return 1
   fi
 
   for d in a a/b a/b/c; do
-    if [ ! -d $repo_dir/tarball_foo/$d ]; then
-      echo "*** Error not found directory: $repo_dir/tarball_foo/$d"
+    if [ ! -d $repo_dir/target/tarball_foo/$d ]; then
+      echo "*** Error not found directory: $repo_dir/target/tarball_foo/$d"
       return 1
     else
-      echo "*** Ingested directory: $repo_dir/tarball_foo/$d"
+      echo "*** Ingested directory: $repo_dir/target/tarball_foo/$d"
 
       for f in 1 2 3; do
-        file=$repo_dir/tarball_foo/$d/$f.txt
+        file=$repo_dir/target/tarball_foo/$d/$f.txt
         if [ ! -f $file ] || [ $(wc -c <$file) -ne 2048 ]; then
           echo "*** Error not found file: $file"
           return 1
@@ -76,7 +76,7 @@ cvmfs_run_test() {
     fi
   done
 
-  file=$repo_dir/tarball_foo/d/e/f/foo.txt
+  file=$repo_dir/target/tarball_foo/d/e/f/foo.txt
   file_size=$(wc -c <$file)
   if [ ! -f $file ] || [ $file_size -ne 5120 ]; then
     echo "*** Error not found file of size 5120: $file"
